# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
    assets:
        css:
            inputs:
                - %kernel.root_dir%/Resources/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
                - %kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.css
                - @GreibitPanelAdminBundle/Resources/public/css/sb-admin.css
                - @GreibitPanelAdminBundle/Resources/public/css/crud.css
            filters:
                - lessphp
                - cssrewrite
            output: css/app.css
        js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
                - @GreibitPanelAdminBundle/Resources/public/js/plugins/metisMenu/jquery.metisMenu.js
                - @GreibitPanelAdminBundle/Resources/public/js/sb-admin.js
            output: js/app.js