parameters:
#    jordi_llonch_crud_generator.example.class: Greibit\CrudGeneratorBundle\Example

services:
#    jordi_llonch_crud_generator.example:
#        class: %jordi_llonch_crud_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
