parameters:
#    greibit_demo.example.class: Greibit\DemoBundle\Example

services:
#    greibit_demo.example:
#        class: %greibit_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
